image: node:8.4.0

cache:
 paths:
  - node_modules/

services:
 - mongo:3.4.9

before_script:
  - export DATABASE_URL=mongodb://mongo:27017
  - export PLENUUM_BOT_EMAIL=bot@plenuum.com
  - export PLENUUM_BOT_PWD=Cocobongo1
  - export ADMIN_PASSWORD=incline diadem passed hoop
  - export WEBAPP_DOMAIN=http://localhost:3000
  - export ADMIN_DOMAIN=http://localhost:8081
  - npm i --silent

tests:
 variables: {
  NODE_ENV: "test",
 }
 script:
  - NODE_ENV=$NODE_ENV npm start