image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - apk add git openssh
  - pip install docker-compose

#  - docker-compose --version
#  - mkdir -p ~/.ssh
#  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
#  - chmod 600 ~/.ssh/id_rsa
#  - eval "$(ssh-agent -s)"
#  - ssh-add ~/.ssh/id_rsa
#  - ssh-keyscan -H 'dev.plenuum.com' >> ~/.ssh/known_hosts

stages:
  - test
  - review

testing:
  script:
    - docker-compose -f docker-compose-test.yml up -d
    - docker exec -i plenuumbe npm run start-ci-test
    - docker-compose stop
  stage: test
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_PROJECT_PATH_SLUG-$CI_ENVIRONMENT_SLUG
  only:
    - branches
  except:
    - master