version: "2.0.1"
services:
  web:
    build: .
    expose:
      - "5000"
    ports:
      - "5000:5000"
    links:
      - mongo
    container_name: plenuumbe
    depends_on:
      - mongo
    tty: true
    stdin_open: true
    command: 'bash'
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
    container_name: plenuummongo
